service: tongueTwister

provider:
  name: aws
  runtime: nodejs18.x
  stage: prod
  region: eu-west-1
  memorySize: 128
  timeout: 5
  environment:
    ALEXA_SKILL_ID: amzn1.ask.skill.d82254be-0570-432a-9148-30d6ef61b071

functions:
  tongueTwister:
    handler: index.handler
    name: ${self:service}-${self:provider.stage}
    events:
      - alexaSkill: ${self:provider.environment.ALEXA_SKILL_ID}
